#ifndef _SHOOTERCLIENT_WIN64_SHIPPING_DEF_H_
#define _SHOOTERCLIENT_WIN64_SHIPPING_DEF_H_

#define GAME_GWORLD                                         (0x2F70070)
#define GAME_GENGINE                                        (0x2F6D6F8)
#define GAME_NAMES_PTR                                      (0x2E6D0F8)
#define GAME_PERSISTENT_LEVEL_OFFSET                        (0x30)
#define GAME_GAMEINSTANCE_OFFSET                            (0x160)
#define GAME_LOCALPLAYER_OFFSET                             (0x38)
#define GAME_PLAYERCONTROLLER_OFFSET                        (0x30)
#define GAME_ALL_ACTORS_OFFSET                              (0x98)
#define GAME_OBJ_NAME_OFFSET                                (0x18)
#define GAME_MEDIUM_FONT                                    (0x70)
#define GAME_CANVAS_OFFSET                                  (0x380)
#define GAME_ACKNOWLEDEGED_PAWN_OFFSET                      (0x3B0)
#define GAME_CONTROLROTATION_OFFSET                         (0x398)
#define GAME_PLAYERCONTROLLER_HUD_OFFSET                    (0x3C0)
#define GAME_PLAYER_CAMERA_MANAGER                          (0x3C8)
#define GAME_CAMERACACHEPRIVATE                             (0x1A20)
#define GAME_CAMERA_POV                                     (0x10)
#define GAME_CAMERA_ROTATION                                (0xC)
#define GAME_CAMERA_LOCATION                                (0x0)
#define GAME_CAMERA_FOV                                     (0x18)
#define GAME_PAWN_PLAYERSTATE_OFFSET                        (0x350)
#define GAME_PAWN_HEALTH_OFFSET                             (0x92C)
#define GAME_PAWN_NAME                                      (0x438)
#define GAME_PAWN_ROOTCOMMENT                               (0x158)
#define GAME_PAWN_LOCATION                                  (0x164)
#define GAME_GET_CAMERADAMAGESTARTLOCATION_OFFSET           (0x524080)
#define GAME_WORLD_TO_SCREEN_OFFSET                         (0x1542850)
#define GAME_LINEOFSIGHTTO_OFFSET                           (0x148B970)
#define GAME_GET_VIEWPORT_SIZE                              (0x175BD00)
#define GAME_DRAWTEXT_OFFSET                                (0x155E920)
#define GAME_DRAW_HUD_OFFSET                                (0x155E280)
#define GAME_DRAW_RECT_OFFSET                               (0x155E870)
#define GAME_DRAW_LINE_OFFSET                               (0x155E350)


#endif //_SHOOTERCLIENT_WIN64_SHIPPING_DEF_H_
